CREATE TABLE "PUBLIC"."AUDIT"(
"ID" CHARACTER VARYING(32) NOT NULL ,
"TYPE" INTEGER,
"TIME" TIMESTAMP,
"IP" VARCHAR(20),
"SUCCESS" INTEGER,
"EMPCODE" VARCHAR(20),
"DESCRIPTION" VARCHAR(2000),
PRIMARY KEY("ID")
);
CREATE TABLE "PUBLIC"."EMP_STATUS"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"EMPCODE" CHARACTER VARYING(20 CHAR),
"STATUS" INTEGER,
PRIMARY KEY("ID")
);