CREATE TABLE "PUBLIC"."WORKCHECK_D"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"DEPART" CHARACTER VARYING(20 CHAR),
"DEPART2" CHARACTER VARYING(20 CHAR),
"EMPCODE" CHARACTER VARYING(20 CHAR),
"EMPNAME" CHARACTER VARYING(50 CHAR),
"STARTTIME" CHARACTER VARYING(20 CHAR),
"STARTLOCATION" CHARACTER VARYING(100 CHAR),
"ENDTIME" CHARACTER VARYING(20 CHAR),
"ENDLOCATION" CHARACTER VARYING(100 CHAR),
"DATE" DATE,
"EXPLAIN" CHARACTER VARYING(500 CHAR),
PRIMARY KEY("ID")
);

CREATE TABLE "PUBLIC"."EAT_D"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"DEPART" CHARACTER VARYING(20 CHAR),
"DEPART2" CHARACTER VARYING(20 CHAR),
"EMPCODE" CHARACTER VARYING(20 CHAR),
"EMPNAME" CHARACTER VARYING(50 CHAR),
"EATTYPE" CHARACTER(20 CHAR),
"EATLOCATION" CHARACTER VARYING(100 CHAR),
"EATTIME" CHARACTER VARYING(50 CHAR),
"STARTTIME" CHARACTER VARYING(50 CHAR),
"ENDTIME" CHARACTER VARYING(50 CHAR),
"DATE" DATE,
"EXPLAIN" CHARACTER VARYING(500 CHAR),
PRIMARY KEY("ID")
);
