UPDATE MENU SET MENUURL='/plan.do?action=feedback_frame' WHERE MENUCODE='083';

CREATE TABLE "PUBLIC"."FUNDS_BUDGET"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"PJCODE" CHARACTER VARYING(20 CHAR),
"PJNAME" CHARACTER VARYING(50 CHAR),
"DEPARTCODE" CHARACTER VARYING(20 CHAR),
"DEPARTNAME" CHARACTER VARYING(50 CHAR),
"QTKYSR" INTEGER,
"XMXJ" INTEGER,
"CLF" INTEGER,
"GZ" INTEGER,
"SJF" INTEGER,
"WXF" INTEGER,
"SYF" INTEGER,
"SBF" INTEGER,
"GLF" INTEGER,
PRIMARY KEY("ID")
);
