DROP VIEW VIEW_EMP;
DROP VIEW VIEW_TRAIN;
DROP VIEW VIEW_WORKCHECK;
DROP VIEW VIEW_WORKREPORT;

ALTER TABLE EMPLOYEE ALTER COLUMN MAINJOB TYPE VARCHAR(200);
ALTER TABLE EMPLOYEE ALTER COLUMN SECJOB TYPE VARCHAR(200);
ALTER TABLE EMP_POS ALTER COLUMN POSCODE TYPE VARCHAR(20);
ALTER TABLE PLAN ALTER COLUMN EMPCODE TYPE VARCHAR(200);
ALTER TABLE PLAN ALTER COLUMN EMPNAME TYPE VARCHAR(200);
ALTER TABLE PLAN ALTER COLUMN ORDERCODE TYPE VARCHAR(20);