ALTER TABLE WORKREPORT ALTER COLUMN AMOUNT TYPE NUMERIC(5,1);
ALTER TABLE PROJECT ALTER COLUMN CODE TYPE VARCHAR(100);
ALTER TABLE PROJECT ALTER COLUMN NAME TYPE VARCHAR(100);
ALTER TABLE PROJECT_D ALTER COLUMN PJCODE TYPE VARCHAR(100);
ALTER TABLE PLAN ALTER COLUMN PJCODE TYPE VARCHAR(100);
ALTER TABLE WORKREPORT ALTER COLUMN PJCODE TYPE VARCHAR(100);