ALTER TABLE WORKREPORT ALTER COLUMN AMOUNT TYPE NUMERIC(5,1);

ALTER TABLE PLAN ALTER COLUMN PJCODE TYPE VARCHAR(200);
ALTER TABLE PROJECT_D ALTER COLUMN PJCODE TYPE VARCHAR(200);

ALTER TABLE PLAN ADD COLUMN EMP_NOTE VARCHAR(500);
ALTER TABLE PLAN ADD COLUMN TEAM_NOTE VARCHAR(500);
ALTER TABLE PLAN ADD COLUMN PLAN_NOTE VARCHAR(500);
