ALTER TABLE PLAN add COLUMN DEALEMPCODE VARCHAR(20);
ALTER TABLE PLAN add COLUMN DEALEMPNAME VARCHAR(20);

ALTER TABLE WORKREPORT add COLUMN BACKBZ VARCHAR(1000);
ALTER TABLE WORKREPORT add COLUMN BACKEMPCODE VARCHAR(20);
ALTER TABLE WORKREPORT add COLUMN BACKEMPNAME VARCHAR(20);

UPDATE MENU SET MENUURL='workreport.do?action=frame_audit' WHERE MENUCODE='022';