UPDATE MENU SET MENUURL='/plan.do?action=feedback_frame' WHERE MENUCODE='083';

/* 经费预算表 */
CREATE TABLE "PUBLIC"."FUNDS_BUDGET"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"PJCODE" CHARACTER VARYING(20 CHAR),
"PJNAME" CHARACTER VARYING(50 CHAR),
"DEPARTCODE" CHARACTER VARYING(20 CHAR),
"DEPARTNAME" CHARACTER VARYING(50 CHAR),
"QTKYSR" INTEGER,
"XMXJ" INTEGER,
"CLF" INTEGER,
"GZ" INTEGER,
"SJF" INTEGER,
"WXF" INTEGER,
"SYF" INTEGER,
"SBF" INTEGER,
"GLF" INTEGER,
PRIMARY KEY("ID")
);

UPDATE WORKREPORT SET OVER_AMOUNT=0 WHERE OVER_AMOUNT IS NULL;

DELETE FROM USER_MENU WHERE (MENUCODE='130' OR MENUCODE='131') AND EMPCODE!='009';

UPDATE MENU SET ORDERCODE=98 WHERE MENUCODE='009';
UPDATE MENU SET ORDERCODE=99 WHERE MENUCODE='091';

/* 整件组成表(由元件目录生成) */
CREATE TABLE "PUBLIC"."ZJB"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"PJCODE" CHARACTER VARYING(20 CHAR),
"XH" INTEGER,
"CCH" CHARACTER VARYING(20 CHAR),
"LEVEL" INTEGER,
"ZJH" CHARACTER VARYING(50 CHAR),
"BB" CHARACTER VARYING(20 CHAR),
"MC" CHARACTER VARYING(50 CHAR),
"SL" INTEGER,
"ZSL" INTEGER,
"BZ" CHARACTER VARYING(200 CHAR),
PRIMARY KEY("ID")
);

/*整件元件明细表*/
CREATE TABLE "PUBLIC"."ZJB_YJ"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"ZJID" CHARACTER VARYING(32 CHAR),
"ZJID_S" CHARACTER VARYING(32 CHAR),
"TYPE" CHARACTER VARYING(10 CHAR),
"XH" INTEGER,
"FM" CHARACTER VARYING(20 CHAR),
"BH" CHARACTER VARYING(50 CHAR),
"MC" CHARACTER VARYING(100 CHAR),
"ZRBH" CHARACTER VARYING(50 CHAR),
"ZRSL" INTEGER,
"ZSL" INTEGER,
"BZ" CHARACTER VARYING(200 CHAR),
PRIMARY KEY("ID")
);

/* 整件组成表(由导入) */
CREATE TABLE "PUBLIC"."ZJZCB"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"PJCODE" CHARACTER VARYING(20 CHAR),
"XH" INTEGER,
"CCH" CHARACTER VARYING(20 CHAR),
"LEVEL" INTEGER,
"ZJH" CHARACTER VARYING(50 CHAR),
"BB" CHARACTER VARYING(20 CHAR),
"MC" CHARACTER VARYING(50 CHAR),
"SL" INTEGER,
"ZSL" INTEGER,
"BZ" CHARACTER VARYING(200 CHAR),
PRIMARY KEY("ID")
);


/* 整件投产表 */
CREATE TABLE "PUBLIC"."TCB"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"XH" INTEGER,
"PJCODE" CHARACTER VARYING(20 CHAR),
"ZJH" CHARACTER VARYING(50 CHAR),
"MC" CHARACTER VARYING(50 CHAR),
"DTZJS" INTEGER,
"TS" INTEGER,
"TSBFS" INTEGER,
"TCZS" INTEGER,
"TZD" CHARACTER VARYING(20 CHAR),
"TZL" CHARACTER VARYING(20 CHAR),
"QCYS" CHARACTER VARYING(20 CHAR),
"YQRQ" CHARACTER VARYING(20 CHAR),
"CZDW" CHARACTER VARYING(20 CHAR),
"DW" CHARACTER VARYING(20 CHAR),
"LXR" CHARACTER VARYING(20 CHAR),
"DH" CHARACTER VARYING(20 CHAR),
"BZ" CHARACTER VARYING(200 CHAR),
PRIMARY KEY("ID")
);

/* 投产全程管理跟踪表 */
CREATE TABLE "PUBLIC"."TCGZB"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"TCID" CHARACTER VARYING(32 CHAR),
"STATUS" CHARACTER VARYING(20 CHAR),
"JGQK" CHARACTER VARYING(1000 CHAR),
"TSQK" CHARACTER VARYING(1000 CHAR),
"CCJL" CHARACTER VARYING(1000 CHAR),
"RWHF" CHARACTER VARYING(200 CHAR),
"RWHFFK" CHARACTER VARYING(200 CHAR),
"TSQSSJ" TIMESTAMP,
"TSJZSJ" TIMESTAMP,
PRIMARY KEY("ID")
);

/* 投产跟踪任务划分表 */
CREATE TABLE "PUBLIC"."TCGZB_RWHF"(
"ID" CHARACTER VARYING(32 CHAR) NOT NULL ,
"TCGZID" CHARACTER VARYING(32 CHAR),
"EMPCODE" CHARACTER VARYING(20 CHAR),
"EMPNAME" CHARACTER VARYING(50 CHAR),
PRIMARY KEY("ID")
);

INSERT INTO DICT VALUES('1','加工生产完成','','TCGZB','STATUS');
INSERT INTO DICT VALUES('2','交付设计师','','TCGZB','STATUS');
INSERT INTO DICT VALUES('3','总体联试','','TCGZB','STATUS');
INSERT INTO DICT VALUES('4','外场联试','','TCGZB','STATUS');
INSERT INTO DICT VALUES('5','已调完','','TCGZB','STATUS');
INSERT INTO DICT VALUES('6','交付出所','','TCGZB','STATUS');

INSERT INTO DICT VALUES('1','文件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('2','零件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('3','整件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('4','软件整件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('5','标准件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('6','外购件','','ZJB_YJ','TYPE');
INSERT INTO DICT VALUES('7','材料','','ZJB_YJ','TYPE');
